# 서버 설정
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /api
  tomcat:
    threads:
      max: 200
    max-connections: 10000

# SPIRNG 설정
spring:
  application:
    name: spot
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  profiles:
    group:
      local:
        - local
    active: local
    include: db
  thymeleaf:
    check-template-location: false