# 스프링 설정
spring:
  application:
    name: spot-be
  profiles:
    active: local
  thymeleaf:
    check-template-location: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
# 서버 설정
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /api
  tomcat:
    threads:
      max: 200
    max-connections: 10000

# SPIRNG 설정

# SWAGGER
springdoc:
  show-login-endpoint: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    display-request-duration: true
    disable-swagger-default-url: true # petStore default로 들어가는 것 끄기
    urls:
      - name: "Default Server URL"
        url: "/api/v3/api-docs"

  default-produces-media-type: application/json

logging:
  level:
    org:
      springframework:
        security: DEBUG

klaytn:
  bithumb:
    kaia:
      krw:
        api:
          url: https://api.bithumb.com/v1/ticker?markets=KRW-KAIA
