name: Auto assign

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions: write-all

jobs:
  auto_add:
    name: Auto add reviewer and assignee
    runs-on: ubuntu-latest
    steps:
      - name: Set Reviewers and Assignee
        run: |
          case "$AUTHOR" in
              immyeong)
                  reviewers=("42kko" "dalcheonroadhead")
                  ;;
              42kko)
                  reviewers=("dalcheonroadhead" "eunSoft")
                  ;;
              dalcheonroadhead)
                  reviewers=("eunSoft" "hxcva1")
                  ;;
              eunSoft)
                  reviewers=("hxcva1" "immyeong")
                  ;;
              hxcva1)
                  reviewers=("immyeong" "42kko")
                  ;;
              *)
                  echo "No reviewers assigned"
                  exit 1
                  ;;
          esac

          echo "Author: $AUTHOR"
          echo "Reviewers: ${reviewers[*]}"

          # PR에 Assignee 추가
          gh pr edit "${{ github.event.pull_request.number }}" --add-assignee "$AUTHOR"

          # 리뷰어를 개별적으로 추가
          for reviewer in "${reviewers[@]}"; do
            gh pr edit "${{ github.event.pull_request.number }}" --add-reviewer "$reviewer"
          done
    env:
      GH_TOKEN: ${{ secrets.PR_ASSIGN_KEY }}
      AUTHOR: ${{ github.event.sender.login }}
