name: Auto assign

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions: write-all

jobs:
  auto_add:
    name: Auto add reviewer and assignee
    runs-on: ubuntu-latest
    steps:
      - run: |
          case "$AUTHOR" in
              immyeong)
                  reviewers=("42kko" "dalcheonroadhead")
                  ;;
              42kko)
                  reviewers=("dalcheonroadhead" "eunSoft")
                  ;;
              dalcheonroadhead)
                  reviewers=("eunSoft" "hxcva1")
                  ;;
              eunSoft)
                  reviewers=("hxcva1" "immyeong")
                  ;;
              hxcva1)
                  reviewers=("immyeong" "42kko")
                  ;;
              *)
                  echo "No reviewers assigned"
                  exit 1
                  ;;
          esac
          reviewers_str=$(IFS=,; echo "${reviewers[*]}")
          echo "Author: $AUTHOR"
          echo "Reviewers: $reviewers_str"
          gh pr edit ${{ github.event.pull_request.number }} --add-assignee "$AUTHOR" --add-reviewer "$reviewers_str" --repo "$GITHUB_REPOSITORY"
    env:
      GH_TOKEN: ${{ secrets.PR_ASSIGN_KEY }}
      AUTHOR: ${{ github.event.sender.login }}
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
