name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - develop # 필요하면 다른 브랜치로 변경 가능

permissions:
  id-token: write  # OIDC를 이용한 AWS 인증을 위해 필요
  contents: read   # actions/checkout을 위해 필요

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build --no-daemon

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::160885287796:role/GithubActionsOIDC # IAM Role 변경 필요
          role-session-name: GitHubActionsSession
          aws-region: ap-northeast-2 # AWS 리전 변경 필요

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_NAME: backend-repo # ECR 리포지토리 이름 변경 가능
        run: |
          # Docker 이미지 빌드 및 ECR에 Push
          docker build -t $ECR_REGISTRY/$IMAGE_NAME:latest .
          docker push $ECR_REGISTRY/$IMAGE_NAME:latest