name: Auto assign

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions: write-all

jobs:

### 디스코드에 알림을 보냅니다.
  notify_discord:
    name: Send Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send PR Notification to Discord
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR="${{ github.event.sender.login }}"
          PR_URL="${{ github.event.pull_request.html_url }}"

          # 리뷰어 목록 가져오기 (JSON 파싱)
          REVIEWERS_JSON=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq '.requested_reviewers')

          echo "🟢 리뷰어 JSON 데이터: $REVIEWERS_JSON"

          # 리뷰어 정보를 JSON에서 파싱하여 Discord 필드에 맞게 변환
          REVIEWERS_FIELD=""
          for row in $(echo "${REVIEWERS_JSON}" | jq -c '.[]'); do
            LOGIN=$(echo "$row" | jq -r '.login')
            AVATAR_URL=$(echo "$row" | jq -r '.avatar_url')

          # Discord Embed 필드에 추가
          REVIEWERS_FIELD="${REVIEWERS_FIELD} {
            \"name\": \"리뷰어\",
            \"value\": \"![${LOGIN}](${AVATAR_URL}) [$LOGIN](https://github.com/${LOGIN})\",
            \"inline\": true
          },"
          done

          # 만약 리뷰어가 없다면 기본 메시지 설정
          if [ -z "$REVIEWERS_FIELD" ]; then
            REVIEWERS_FIELD="{
              \"name\": \"리뷰어\",
              \"value\": \"리뷰어가 없습니다.\",
              \"inline\": true
            }"
          fi

          echo "데이터 정리완료, 디스코드 알림을 보냅니다."

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"embeds\": [
                {
                  \"color\": 16776960,
                  \"title\": \"📌 Pull Request Created/Updated\",
                  \"description\": \"새로운 PR이 생성되었거나 업데이트되었습니다.\",
                  \"fields\": [
                    {
                      \"name\": \"PR 제목\",
                      \"value\": \"[$PR_TITLE]($PR_URL)\",
                      \"inline\": false
                    },
                    {
                      \"name\": \"작성자\",
                      \"value\": \"[$PR_AUTHOR](https://github.com/$PR_AUTHOR)\",
                      \"inline\": true
                    },
                    $REVIEWERS_FIELD
                  ],
                  \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"
                }
              ]
            }" \
            "$DISCORD_URL"
    env:
      TOKEN: ${{ secrets.PR_WEBHOOK_PAT }}
      DISCORD_URL: ${{ secrets.DISCORD_WEBHOO_BE }}
